// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWd-QZNXLGnGcIVeutn4MenyrluOMxm4w',
    appId: '1:502943953589:web:59d482b23a45d6223f44fc',
    messagingSenderId: '502943953589',
    projectId: 'izaan-flutter-chat-app',
    authDomain: 'izaan-flutter-chat-app.firebaseapp.com',
    storageBucket: 'izaan-flutter-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2qdAOTkOBy8iwwXCdWMSxQzlCVFOheE0',
    appId: '1:502943953589:android:1d7d21086ffdd3843f44fc',
    messagingSenderId: '502943953589',
    projectId: 'izaan-flutter-chat-app',
    storageBucket: 'izaan-flutter-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAZYkkAcy3g_WyROEzoPpE_4k_XAbgAmQ',
    appId: '1:502943953589:ios:f11d0e2942841e603f44fc',
    messagingSenderId: '502943953589',
    projectId: 'izaan-flutter-chat-app',
    storageBucket: 'izaan-flutter-chat-app.appspot.com',
    iosClientId: '502943953589-acdn95aefkutimr2lm2k2ncii4ld4sf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
